name: GitHub Search Script 2.0

on:
  schedule:
    - cron: "*/15 * * * *"  
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:

      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false 
          fetch-depth: 0 

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'


      - name: Create files if not exists
        run: |
          touch processed_users.txt
          touch repos_found.txt

      - name: Install dependencies
        run: npm install


      - name: Run the GitHub Search script
        env:
          GITHUB_TOKEN1: ${{ secrets.TOKEN1 }}
          GITHUB_TOKEN2: ${{ secrets.TOKEN2 }}
          GITHUB_TOKEN3: ${{ secrets.TOKEN3 }}
          GITHUB_TOKEN4: ${{ secrets.TOKEN4 }}
          GITHUB_TOKEN5: ${{ secrets.TOKEN5 }}
        run: node script.js


      - name: Commit and push changes
        run: |
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"
          git add -f processed_users.txt repos_found.txt
          git commit -m "Update processed_users and repos_found from GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



